/*
 * Procesamiento.h
 *
 *  Created on: Oct 26, 2018
 *      Author: federico
 */

#ifndef PROJECTS_DECIBELIMETRO_V0_0_PROCESAMIENTO_INC_PROCESAMIENTO_H_
#define PROJECTS_DECIBELIMETRO_V0_0_PROCESAMIENTO_INC_PROCESAMIENTO_H_


void initTaskDSP ();

#endif /* PROJECTS_DECIBELIMETRO_V0_0_PROCESAMIENTO_INC_PROCESAMIENTO_H_ */
